import pytz

# -----------------------------
# Constants & Dictionaries
# -----------------------------
LOCATION_DICT = {
    'Newark Airport': 1,
 'Bronx - Allerton/Pelham Gardens': 2,
 'Bronx - Arden Heights': 3,
 'Staten Island - Arrochar/Fort Wadsworth': 4,
 'Queens - Astoria': 5,
 'Queens - Astoria Park': 6,
 'Queens - Auburndale': 7,
 'Queens - Baisley Park': 8,
 'Brooklyn - Bath Beach': 9,
 'Manhattan - Battery Park': 10,
 'Manhattan - Battery Park City': 11,
 'Brooklyn - Bay Ridge': 12,
 'Queens - Bay Terrace/Fort Totten': 13,
 'Queens - Bayside': 14,
 'Brooklyn - Bedford': 15,
 'Bronx - Bedford Park': 16,
 'Queens - Bellerose': 17,
 'Bronx - Belmont': 18,
 'Brooklyn - Bensonhurst East': 19,
 'Brooklyn - Bensonhurst West': 20,
 'Staten Island - Bloomfield/Emerson Hill': 21,
 'Brooklyn - Boerum Hill': 22,
 'Manhattan - Central Harlem': 23,
 'Manhattan - Central Harlem North': 24,
 'Manhattan - Central Park': 25,
 'Brooklyn - Charlestown/Tottenville': 26,
 'Queens - Breezy Point/Fort Tilden/Riis Beach': 27,
 'Queens - Briarwood/Jamaica Hills': 28,
 'Brooklyn - Brighton Beach': 29,
 'Queens - Broad Channel': 30,
 'Brooklyn - Brooklyn Heights': 31,
 'Brooklyn - Brownsville': 32,
 'Brooklyn - Bushwick North': 33,
 'Brooklyn - Bushwick South': 34,
 'Queens - Cambria Heights': 35,
 'Brooklyn - Canarsie': 36,
 'Brooklyn - Carroll Gardens': 37,
 'Manhattan - Central Harlem South': 38,
 'Brooklyn - Chinatown': 39,
 'Queens - Cambria Heights South': 40,
 'Bronx - City Island': 41,
 'Brooklyn - Cypress Hills': 42,
 'Bronx - East Tremont': 43,
 'Bronx - Edenwald': 44,
 'Bronx - Fieldston': 45,
 'Bronx - Fordham North': 46,
 'Bronx - Claremont/Bathgate': 47,
 'Manhattan - Clinton East': 48,
 'Brooklyn - Clinton Hill': 49,
 'Manhattan - Clinton West': 50,
 'Bronx - Co-Op City': 51,
 'Brooklyn - Cobble Hill': 52,
 'Queens - College Point': 53,
 'Brooklyn - Columbia Street': 54,
 'Brooklyn - Coney Island': 55,
 'Queens - Corona': 56,
 'Bronx - Hunts Point South': 57,
 'Bronx - Kingsbridge': 58,
 'Bronx - Crotona Park': 59,
 'Brooklyn - Crown Heights South': 60,
 'Brooklyn - Crown Heights North': 61,
 'Queens - Fresh Meadows': 62,
 'Queens - Glen Oaks South': 63,
 'Queens - Douglaston': 64,
 'Brooklyn - Downtown Brooklyn/MetroTech': 65,
 'Brooklyn - DUMBO/Vinegar Hill': 66,
 'Brooklyn - East New York': 67,
 'Manhattan - East Chelsea': 68,
 'Bronx - East Concourse/Concourse Village': 69,
 'Queens - East Elmhurst': 70,
 'Brooklyn - East Flatbush/Farragut': 71,
 'Brooklyn - East New York/Pennsylvania Ave': 72,
 'Bronx - Eastchester': 73,
 'Manhattan - East Harlem North': 74,
 'Queens - Flushing Meadows-Corona Park': 75,
 'Brooklyn - Flatlands': 76,
 'Brooklyn - Floyd Bennett Field': 77,
 'Queens - Forest Park/Highland Park': 78,
 'Manhattan - East Village': 79,
 'Brooklyn - East Williamsburg': 80,
 'Brooklyn - Georgetown/Mill Basin': 81,
 'Queens - Elmhurst': 82,
 'Bronx - Spuyten Duyvil/Kingsbridge': 83,
 "Staten Island - Eltingville/Annadale/Prince's Bay": 84,
 'Queens - Fresh Meadows/Union Turnpike': 85,
 'Queens - Far Rockaway': 86,
 'Manhattan - Financial District North': 87,
 'Manhattan - Financial District South': 88,
 'Brooklyn - Flatbush/Ditmas Park': 89,
 'Manhattan - Flatiron': 90,
 'Queens - Glen Oaks North': 91,
 'Queens - Flushing': 92,
 'Bronx - Pelham Parkway North': 93,
 'Bronx - Fordham South': 94,
 'Queens - Forest Hills': 95,
 'Brooklyn - Highland Park': 96,
 'Brooklyn - Fort Greene': 97,
 'Manhattan - East Harlem South': 98,
 'Brooklyn - Kensington South': 99,
 'Queens - LaGuardia AirTrain': 100,
 'Queens - Glen Oaks': 101,
 'Brooklyn - Manhattan Beach': 102,
 'Brooklyn - Manhattan Terrace': 103,
 'Queens - Meadowmere': 104,
 'Brooklyn - New Lots': 105,
 'Brooklyn - Ocean Parkway South': 106,
 'Manhattan - Gramercy': 107,
 'Brooklyn - Gravesend': 108,
 'Staten Island - Great Kills': 109,
 'Brooklyn - Prospect Heights': 110,
 'Brooklyn - Prospect Park': 111,
 'Brooklyn - Greenpoint': 112,
 'Manhattan - Greenwich Village North': 113,
 'Manhattan - Greenwich Village South': 114,
 'Brooklyn - Red Hook': 115,
 'Manhattan - Hamilton Heights': 116,
 'Queens - Hammels/Arverne': 117,
 'Bronx - Riverdale': 118,
 'Bronx - Highbridge': 119,
 'Manhattan - Highbridge Park': 120,
 'Queens - Hillcrest/Pomonok': 121,
 'Brooklyn - Homecrest': 123,
 'Queens - Howard Beach': 124,
 'Manhattan - Hudson Sq': 125,
 'Bronx - Hunts Point': 126,
 'Manhattan - Inwood': 127,
 'Queens - Jackson Heights': 129,
 'Queens - Jamaica': 130,
 'JFK Airport': 132,
 'Brooklyn - Kensington': 133,
 'Queens - Kew Gardens': 134,
 'Manhattan - Lenox Hill West': 135,
 'Bronx - Kingsbridge Heights': 136,
 'Manhattan - Kips Bay': 137,
 'LaGuardia Airport': 138,
 'Queens - Laurelton': 139,
 'Manhattan - Lenox Hill East': 140,
 'Manhattan - Lincoln Square East': 141,
 'Manhattan - Lincoln Square West': 142,
 'Manhattan - Little Italy': 143,
 'Manhattan - Little Italy/NoLiTa': 144,
 'Queens - Long Island City/Hunters Point': 145,
 'Queens - Maspeth/Middle Village': 146,
 'Queens - Murray Hill': 147,
 'Brooklyn - Navy Yard': 148,
 'Brooklyn - Madison': 149,
 'Brooklyn - New Lots North': 150,
 'Manhattan - Manhattan Valley': 151,
 'Queens - Neponsit': 152,
 'Manhattan - Marble Hill': 153,
 'Brooklyn - Marine Park/Floyd Bennett Field': 154,
 'Queens - North Flushing': 155,
 'Staten Island - Mariners Harbor': 156,
 'Queens - Maspeth': 157,
 'Manhattan - Meatpacking/West Village West': 158,
 'Queens - Queensboro Hill': 159,
 'Queens - Middle Village': 160,
 'Manhattan - Midtown Center': 161,
 'Manhattan - Midtown East': 162,
 'Manhattan - Midtown North': 163,
 'Queens - Ridgewood': 164,
 'Brooklyn - Midwood': 165,
 'Manhattan - Morningside Heights': 166,
 'Bronx - Morrisania/Melrose': 167,
 'Bronx - Soundview Park': 168,
 'Bronx - Soundview/Morrison': 169,
 'Manhattan - Murray Hill': 170,
 'Queens - Murray Hill-Queens': 171,
 'Queens - Rockaway Park': 172,
 'Queens - North Corona': 173,
 'Bronx - Norwood': 174,
 'Queens - Oakland Gardens': 175,
 'Staten Island - Oakwood': 176,
 'Brooklyn - Ocean Hill': 177,
 'Queens - Seaside': 178,
 'Queens - Old Astoria': 179,
 'Queens - Ozone Park': 180,
 'Brooklyn - Park Slope': 181,
 'Bronx - Parkchester': 182,
 'Bronx - Pelham Bay': 183,
 'Manhattan - Stuyvesant Town/Peter Cooper Village': 184,
 'Brooklyn - Sunset Park': 185,
 'Manhattan - Penn Station/Madison Sq West': 186,
 'Staten Island - Port Richmond': 187,
 'Brooklyn - Prospect-Lefferts Gardens': 188,
 'Manhattan - Turtle Bay': 189,
 'Brooklyn - Williamsburg': 190,
 'Queens - Queens Village': 191,
 'Queens - Whitestone': 192,
 'Queens - Willets Point': 193,
 'Bronx - Woodlawn/Wakefield': 194,
 'Brooklyn - Windsor Terrace South': 195,
 'Queens - Rego Park': 196,
 'Staten Island - Willowbrook': 197,
 'Staten Island - Woodrow': 198,
 'Bronx - Rikers Island': 199,
 'Brooklyn - Windsor Terrace North': 200,
 'Brooklyn - Windsor Terrace East': 201,
 'Manhattan - Roosevelt Island': 202,
 'Queens - Woodhaven South': 203,
 'Queens - Woodside North': 204,
 'Queens - Saint Albans': 205,
 'Staten Island - Saint George/New Brighton': 206,
 'Staten Island - West New Brighton': 207,
 'Staten Island - West Shore': 208,
 'Manhattan - Seaport': 209,
 'Brooklyn - Sheepshead Bay': 210,
 'Manhattan - SoHo': 211,
 'Bronx - Soundview/Bruckner': 212,
 'Staten Island - Willowbrook Park': 213,
 'Staten Island - South Beach/Dongan Hills': 214,
 'Queens - South Jamaica': 215,
 'Staten Island - Tottenville': 216,
 'Brooklyn - South Williamsburg': 217,
 'Queens - Springfield Gardens North': 218,
 'Staten Island - Stapleton': 221,
 'Brooklyn - Starrett City': 222,
 'Queens - Steinway': 223,
 'Brooklyn - Stuyvesant Heights': 224,
 'Queens - Sunnyside': 225,
 'Brooklyn - Sunset Park East': 226,
 'Brooklyn - Sunset Park West': 227,
 'Manhattan - Sutton Place/Turtle Bay North': 228,
 'Manhattan - Times Sq/Theatre District': 229,
 'Manhattan - TriBeCa/Civic Center': 230,
 'Manhattan - Two Bridges/Seward Park': 231,
 'Manhattan - UN/Turtle Bay South': 232,
 'Manhattan - Union Sq': 233,
 'Queens - University Heights/Morris Heights': 234,
 'Manhattan - Upper East Side North': 235,
 'Manhattan - Upper East Side South': 236,
 'Manhattan - Upper West Side North': 237,
 'Manhattan - Upper West Side South': 238,
 'Bronx - Van Cortlandt Park': 239,
 'Bronx - Van Cortlandt Village': 240,
 'Bronx - Van Nest/Morris Park': 241,
 'Manhattan - Washington Heights North': 242,
 'Manhattan - Washington Heights South': 243,
 'Staten Island - West Brighton': 244,
 'Brooklyn - West Brighton': 245,
 'Brooklyn - Williamsburg (North Side)': 246,
 'Brooklyn - Williamsburg (South Side)': 247,
 'Brooklyn - Windsor Terrace': 248,
 'Queens - Woodhaven': 249,
 'Queens - Woodside': 250,
 'Manhattan - World Trade Center': 251,
 'Manhattan - Yorkville East': 252,
 'Manhattan - Yorkville West': 253,
 'Bronx - Central Bronx': 254,
 'Bronx - Bronx Park': 255,
 'Bronx - Pelham Parkway': 256,
 'Bronx - Crotona Park East': 257,
 'Bronx - Morrisania': 258,
 'Bronx - Soundview': 259,
 'Bronx - Throgs Neck': 260,
 'Bronx - West Farms': 261,
 'Bronx - Westchester Village/Unionport': 262,
 'Bronx - Williamsbridge/Olinville': 263
}

WEATHER_DICT = {
    0: "Clear sky", 1: "Mainly clear", 2: "Partly cloudy", 3: "Overcast",
    51: "Light drizzle", 53: "Moderate drizzle", 55: "Dense drizzle",
    61: "Slight rain", 63: "Moderate rain", 65: "Heavy rain",
    71: "Slight snow fall", 73: "Moderate snow fall", 75: "Heavy snow fall"
}

NY_TZ = pytz.timezone('America/New_York')
HIST_PATH = "templates/historical_data/hist_data.csv"  # expects cols: [PULocationID, pickup_hour, ride_count, ...]

REQUIRED_TARGET_DERIVED = [
    'ride_count_lag_1', 'ride_count_lag_24', 'ride_count_lag_168',
    'ride_count_roll_mean_3', 'ride_count_roll_std_3'
]

HIST_PATH = "templates/historical_data/hist_data.csv"